version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/shroomie
      - ./.env:/app/.env
    environment:
      - PORT=5000
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped